require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

target 'ChessVibe' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])


  target 'ChessVibeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ChessVibe-tvOS' do
  # Pods for ChessVibe-tvOS

  target 'ChessVibe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


# Multiple commands produce '/Users/lleeoochen/Library/Developer/Xcode/DerivedData/ChessVibe-gmgkvnuxxbzcaleplxbcdubwwvoa/Build/Intermediates.noindex/ArchiveIntermediates/ChessVibe/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AccessibilityResources.bundle':
# 1) Target 'React-Core.common-AccessibilityResources' has create directory command with output '/Users/lleeoochen/Library/Developer/Xcode/DerivedData/ChessVibe-gmgkvnuxxbzcaleplxbcdubwwvoa/Build/Intermediates.noindex/ArchiveIntermediates/ChessVibe/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AccessibilityResources.bundle'
# 2) Target 'React-Core.common-CoreModulesHeaders-AccessibilityResources' has create directory command with output '/Users/lleeoochen/Library/Developer/Xcode/DerivedData/ChessVibe-gmgkvnuxxbzcaleplxbcdubwwvoa/Build/Intermediates.noindex/ArchiveIntermediates/ChessVibe/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AccessibilityResources.bundle'

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     # if target.name == "React"
#     if target == 'React-Core.common-AccessibilityResources'
#       target.remove_from_project
#     end
#   end
# end